Additional features and CR Changes
hellosign/hellosign-php-sdk pull request #81
Opened 2018-10-25 23:51 UTC by jyoung488

Changes from PR #79 and suggestions from Nate
Adding in these features:
- Adjusting the short circuit methods
- #72: Signer Groups
- Adjusting unit tests

2018-10-26 17:06 UTC, nathanbuchar commented
I think should still test for PHP 5.5 support. I'm sure not all of our users are running PHP 7, and we're not explicitly using and new PHP 7 syntax like Array literals or anonymous functions (as far as I know), so if we can passively support older PHP versions then I think we should

2018-10-26 17:16 UTC, nathanbuchar commented
Probably just a refactoring oversight, but when you cleaned up the short-circuiting logic, you left semicolons at the end of the conditionals:

```php
if ($foo) {
  return $bar;
}; // <- unnecessary semicolon
```

2018-10-26 17:16 UTC, jyoung488 commented
I added v5.5 back in but the Travis tests are failing due to dependencies that require v7.1

2018-10-26 17:17 UTC, nathanbuchar commented
@jyoung488 Ah, so we do have PHP 7 dependencies? In that case, this lib won't work on PHP <7. Is that correct?

2018-10-26 17:48 UTC, jyoung488 commented
@nathanbuchar yeah :( there are several dependencies requiring ^7.1

2018-10-26 17:51 UTC, jyoung488 commented
Also removed the unnecessary semicolons! Thanks for that note - still learning the language so this is super helpful

2018-10-26 23:25 UTC, nathanbuchar commented
@jyoung488 If so, then yeah let's remove PHP 5.5 from Travis CI. We also need to update the README, as it currently says:

> ### Requirements
> The latest version of the SDK requires PHP version 5.5 or higher.

2018-10-26 23:25 UTC, nathanbuchar requested changes

2018-10-26 23:25 UTC, nathanbuchar commented on library/HelloSign/Test/SignatureRequestTest.php
> +        $request->addGroupSigner("Jane Example", "jane@example.com", 2);
+1 for using fake email addresses

2018-10-26 23:25 UTC, nathanbuchar commented on library/HelloSign/AbstractSignatureRequest.php
> +      );
Incorrect indentation

```diff
  $group = new SignerGroup(array(
    'name' => $name
-   )
- );
+ ));
```

2018-10-29 16:06 UTC, jyoung488 commented
@nathanbuchar Thanks! Made these changes.

2018-10-29 18:48 UTC, nathanbuchar approved these changes

2018-10-29 23:35 UTC, merged